analytics.onpremise.enable=false
analytics.integration.enable=true
analytics.project="{\\n  \\"id\\"\: 1327272,\\n  \\"name\\"\: \\"First Project\\",\\n  \\"teamId\\"\: 1307217,\\n  \\"organizationId\\"\: 1355503,\\n  \\"isSampleProject\\"\: false,\\n  \\"canAutoIntegrate\\"\: false\\n}"
analytics.team="{\\n  \\"id\\"\: 1307217\\n}"
analytics.testcloud.integration.enable=false
analytics.testreport.autoupload.enable=false
analytics.testcloud.hub.switchHub.enable=false
